import assert from 'node:assert/strict';import test from 'node:test';
import {BackendFlyPerformance,executeRecordedPerformance,frameAtTime,performanceFingerprint,solveForeleg} from '../web/art-engine.mjs';
import {ART_PALETTE,BRUSH_TOOLS,DRAWING_TECHNIQUES,REQUIRED_ACTION_FIELDS,validateBrainAction} from '../web/flybrain.mjs';
import {signalsForDecision} from '../web/brain-activity.mjs';

function action(index=0,overrides={}){return{intent:'MOVE',targetDirection:index%2?Math.PI/2:0,movementDistance:42+index,curvature:(index%3-.8)*.25,speed:.6,duration:300,brushDown:true,pressure:.55,hesitation:0,exploration:.5,attentionTarget:{kind:'focal_area',point:[400,250]},eraseIntent:false,movementStyle:['sweep','curl','segmented','branch','spiral','loop','jitter','echo','cross','cluster','contour','accent','bold'][index%13],relationshipToExistingMarks:index?'revisit_and_develop':'extend_current_structure',motifReference:index?{decision:index-1}:null,color:ART_PALETTE[index%10],confidence:.8,reason:'Authoritative test action.',phase:'DEVELOPMENT',evaluation:null,scale:1,layerRole:'SECONDARY',motifTransform:index?'repeat':'none',branchingDepth:0,strokeCharacter:'layered',brushTool:BRUSH_TOOLS[index%BRUSH_TOOLS.length],technique:DRAWING_TECHNIQUES[index%DRAWING_TECHNIQUES.length],...overrides}}
function finish(){return action(10,{intent:'FINISH_ARTWORK',movementDistance:0,curvature:0,speed:0,duration:0,brushDown:false,pressure:0,hesitation:0,exploration:0,eraseIntent:false,reason:'FLY_DECLARED_COMPOSITION_COMPLETE',phase:'RESOLUTION',evaluation:{readiness:.9,summary:'The composition is resolved.'}})}

test('action schema is incremental and rejects complete paths',()=>{const a=action();for(const field of REQUIRED_ACTION_FIELDS)assert.ok(field in a);assert.equal(validateBrainAction(a),true);assert.equal(validateBrainAction({...a,path:[[0,0],[1,1]]}),false)});
test('mechanics execute only recorded brain decisions',()=>{const performance=executeRecordedPerformance(11,[action(0),action(1),finish()]);assert.equal(performance.brainDecisions.length,3);assert.equal(performance.events.filter(e=>e.type==='stroke').length,2);assert.equal(performance.status,'EVALUATING');assert.equal(performance.events.at(-1).type,'finish_artwork')});
test('brain direction directly controls physical movement',()=>{const horizontal=executeRecordedPerformance(12,[action(0,{targetDirection:0,curvature:0})]);const vertical=executeRecordedPerformance(12,[action(0,{targetDirection:Math.PI/2,curvature:0})]);const h=horizontal.events.find(e=>e.type==='stroke').points.at(-1),v=vertical.events.find(e=>e.type==='stroke').points.at(-1);assert.ok(h[0]>v[0]);assert.ok(v[1]>h[1])});
test('backend controller accepts server-authoritative observation and events',async()=>{const raw={session_id:'abc',seed:8,status:'CREATED',brain_mode:'LOCAL PROCEDURAL FLY BRAIN',parameters:{},limits:{},brain_decisions:[]};const runner=new BackendFlyPerformance(raw);let request;const observed={currentForelegPosition:[735,48],recentMarks:[],visitedAreas:[],physicalActionCount:0};const serverEvents=[{type:'stroke',timestamp:100,duration:300,points:[[735,48],[700,48]],width:4.32,opacity:.879,color:action(0).color,decision:0,brushTool:action(0).brushTool,technique:action(0).technique}];const mock=async(url,options)=>{request=JSON.parse(options.body);return{ok:true,json:async()=>({action:action(0),observation:observed,events:serverEvents,serverClock:400,state:'RUNNING',brainMode:'LOCAL PROCEDURAL FLY BRAIN',sequence:0})}};await runner.step(mock);assert.deepEqual(request,{sequence:0});assert.deepEqual(runner.session.observations[0].currentForelegPosition,[735,48]);assert.equal(runner.session.events.some(event=>event.type==='stroke'),true);assert.equal(runner.session.brainDecisions.length,1)});
test('all ten full-palette colors survive into physical strokes',()=>{const performance=executeRecordedPerformance(13,ART_PALETTE.map((_,i)=>action(i)));assert.deepEqual(new Set(performance.events.filter(e=>e.type==='stroke').map(e=>e.color)),new Set(ART_PALETTE))});
test('white canvas palette includes visible black',()=>{assert.ok(ART_PALETTE.some(color=>['#000','#000000','#111111','black'].includes(color.toLowerCase())))});
test('mechanics preserve every brain-selected brush and technique',()=>{const actions=BRUSH_TOOLS.map((brushTool,index)=>action(index,{brushTool,technique:DRAWING_TECHNIQUES[index]}));const strokes=executeRecordedPerformance(19,actions).events.filter(event=>event.type==='stroke');assert.deepEqual(strokes.map(event=>event.brushTool),actions.map(item=>item.brushTool));assert.deepEqual(strokes.map(event=>event.technique),actions.map(item=>item.technique))});
test('exact replay is event-only and preserves fingerprint',()=>{const original=executeRecordedPerformance(14,[action(0),action(1),action(2),finish()]);const replay=JSON.parse(JSON.stringify(original));assert.deepEqual(replay.events,original.events);assert.equal(performanceFingerprint(replay),performanceFingerprint(original))});
test('brush and synchronized foreleg share the drawing point',()=>{const performance=executeRecordedPerformance(15,[action()]);const stroke=performance.events.find(e=>e.type==='stroke');const frame=frameAtTime(performance,stroke.timestamp+stroke.duration/2);assert.equal(frame.brushDown,true);assert.deepEqual(frame.handTip,frame.brushPoint)});
test('inverse kinematics preserves requested tip',()=>{const limb=solveForeleg([400,150],[330,230]);assert.deepEqual(limb.tip,[330,230]);assert.ok(Number.isFinite(limb.elbow[0]))});
test('brain activity comes from real observation and decision fields',()=>{const observed={recentMarks:[[[1,2]]],visitedAreas:[[1,2]]};const a=action(2,{motifReference:{decision:1},evaluation:{summary:'Needs contrast.'}});assert.deepEqual(signalsForDecision(observed,a),['perception','memory','evaluation','planning','action']);assert.equal(signalsForDecision({},finish()).at(-1),'completion');const performance=executeRecordedPerformance(16,[a,finish()]);const clusters=performance.events.filter(event=>event.type==='brain_signal').map(event=>event.cluster);for(const cluster of ['perception','memory','evaluation','planning','action','completion'])assert.ok(clusters.includes(cluster))});
